# To use this config export RAILS_DATABASE_ENV=connection_pool
# NOTE: Recommended use only on remote databases highly subjective of migrating location
#
credentials: &credentials
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  port: <%= ENV['RAILS_DATABASE_PORT'] %>
  sslmode: <%= ENV['RAILS_DATABASE_SSLMODE'] %>
  prepared_statements: false
  advisory_locks: false

default: &default
  <<: *credentials
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_template_development

test:
  <<: *default
  database: admin_template_test

production:
  <<: *default
  database: admin_template_production
